name: Security npm dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "19 6 * * MON-FRI" # Every weekday
jobs:
  security-npm-dependency-check:
    name: Project security npm dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_npm_dependency.yml@24d1df5c3dce9e4e26fa204dc9149aee0772c2e9 # v2.14.9
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
